apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: flight-prediction
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: agile-data-science
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gke-retain
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-data
  namespace: flight-prediction
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/part-of: agile-data-science
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gke-retain
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: flight-prediction
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: agile-data-science
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gke-retain
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-data
  namespace: flight-prediction
  labels:
    app.kubernetes.io/name: spark
    app.kubernetes.io/part-of: agile-data-science
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gke-retain
  resources:
    requests:
      storage: 5Gi
