apiVersion: v1
kind: ResourceQuota
metadata:
  name: flight-prediction-quota
  namespace: flight-prediction
  labels:
    app.kubernetes.io/name: flight-prediction
spec:
  hard:
    requests.cpu: "12"
    requests.memory: 24Gi
    limits.cpu: "24"
    limits.memory: 48Gi
    pods: "50"
    requests.storage: 100Gi
