apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gke-retain
  labels:
    app.kubernetes.io/name: flight-prediction
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gke-delete
  labels:
    app.kubernetes.io/name: flight-prediction
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete