apiVersion: v1
kind: ServiceAccount
metadata:
  name: flight-prediction-sa
  namespace: flight-prediction
  labels:
    app.kubernetes.io/name: flight-prediction
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flight-prediction-role
  labels:
    app.kubernetes.io/name: flight-prediction
rules:
  # Pods
  - apiGroups: ['']
    resources: ['pods', 'pods/log', 'pods/exec']
    verbs: ['get', 'list', 'watch']
  # Services
  - apiGroups: ['']
    resources: ['services', 'endpoints', 'events']
    verbs: ['get', 'list', 'watch']
  # ConfigMaps and Secrets
  - apiGroups: ['']
    resources: ['configmaps', 'secrets']
    verbs: ['get', 'list', 'watch']
  # Deployments, StatefulSets
  - apiGroups: ['apps']
    resources: ['statefulsets', 'deployments', 'daemonsets']
    verbs: ['get', 'list', 'watch']
  # Jobs
  - apiGroups: ['batch']
    resources: ['jobs', 'cronjobs']
    verbs: ['get', 'list', 'watch']
  # PVCs
  - apiGroups: ['']
    resources: ['persistentvolumeclaims']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flight-prediction-rolebinding
  labels:
    app.kubernetes.io/name: flight-prediction
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flight-prediction-role
subjects:
  - kind: ServiceAccount
    name: flight-prediction-sa
    namespace: flight-prediction